### ISSUE TITLE
Abuso de properties

### ISSUE THREAD

**Issue by dialvarez1** [IIC2233/Syllabus#34]
¿Es penalizable el utilizar properties con el único fin de hacer un atributo de solo lectura? Todavía más, ¿qué hay de utilizarlas para todos los atributos?

**Comment by rihanuch** [comment]
Hola @dialvarez1 !!
Como idea general, no utilices algo sólo por hacerlo 💭 , sino que tienes que ver cuándo es útil cierta función y cuándo no 🤔 . Lamentablemente no puedo responderte eso 😢 , _PERO_ si te pueden servir las 2 siguientes cosas 😄:

1. La idea es que se utilice ```@property``` cuando sea lógico ✅, no usarlo por usarlo (recuerda que una ```@property``` en general se utiliza como "variable" que depende de otras y que se utiliza bien seguido, o quizás para intervenir algo 🛠 !
2. Quizás una esta [issue](https://github.com/IIC2233/Syllabus-2017-2/issues/131) del semestre pasado te pueda servir! ~(al igual que tú, no entendía muy bien la idea de estas al comienzo)~

PD: Ten en mente que (a pesar de que no se pida explícitamente algo en alguna tarea) se espera que sean creativos 🎨 y traten de hacerlo lo mejor posible 👨‍🎓👩‍🎓  **_aplicando la materia_**  vista 💯 

Ánimo y éxito en la tarea!!

PD2: algún ayudante ~@Arcoirisky~ me dijo que pusiera esto, because reasons 🐱🌚
